monkeybusiness-api:
    env_file: ./.env-compose
    image: fitnesskeeper/monkeybusiness:compose
    ports:
        - "9090:9090"
    links:
        - monkeybusiness-redis
monkeybusiness-redis:
    image: redis:2
    ports:
        - "6379"
